import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "AI Todo List App",
  description: "A simple todo list app generated by while.ai",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50">
        {children}
      </body>
    </html>
  )
}